-- ============================================================
-- Database Schema for Accountant Request Tracker
-- ============================================================

CREATE DATABASE IF NOT EXISTS accountant_tracker;
USE accountant_tracker;

-- Requests table
CREATE TABLE IF NOT EXISTS requests (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    client_name VARCHAR(255) NOT NULL,
    assignee VARCHAR(255) NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_reminder_at TIMESTAMP NULL
);

-- Reminders table (records automated reminders generated by scheduler)
CREATE TABLE IF NOT EXISTS reminders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    request_id BIGINT NOT NULL,
    request_title VARCHAR(255) NOT NULL,
    client_name VARCHAR(255) NOT NULL,
    assignee VARCHAR(255) NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(50) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Sample Demo Data
-- Note: Dates are relative. In production or demo, adjust dates relative to CURRENT_DATE.
INSERT INTO requests (title, client_name, assignee, due_date, status, created_at)
VALUES 
('GST Filing', 'Demo Company A', 'Kumar', DATE_ADD(CURRENT_DATE, INTERVAL 1 DAY), 'OPEN', NOW()),
('TDS Report', 'Demo Company B', 'Ravi', DATE_SUB(CURRENT_DATE, INTERVAL 1 DAY), 'OPEN', NOW()), -- Overdue!
('Audit Report', 'Demo Company C', 'Arun', DATE_ADD(CURRENT_DATE, INTERVAL 7 DAY), 'COMPLETED', NOW()),
('Tax Calculation', 'Demo Company D', 'Priya', DATE_ADD(CURRENT_DATE, INTERVAL 5 DAY), 'IN_PROGRESS', NOW()),
('Annual Financial Statement', 'Demo Company E', 'Kumar', DATE_SUB(CURRENT_DATE, INTERVAL 3 DAY), 'OPEN', NOW()); -- Overdue!
